Task_7/Controllers/AuthorController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Task_7.Interfaces;

namespace Task_7.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorRepository _authorRepository;

        public AuthorController(IRepositoryWrapper repositoryWrapper)
        {
            _authorRepository = repositoryWrapper.AuthorRepository;
        }

        public IActionResult Index()
        {
            var authors = _authorRepository.FindAll().ToList();

            return View(authors);
        }

        public IActionResult Info(Guid id)
        {
            var author = _authorRepository.FindByCondition(x => x.Id == id).FirstOrDefault();

            if (author == null) return RedirectToAction("Index");

            return View(author);
        }
    }
}

Task_7/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Task_7.Interfaces;
using Task_7.Models;
using Task_7.ViewModels;

namespace Task_7.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IPublishingHouseRepository _publishingHouseRepository;

        public BookController(IRepositoryWrapper repositoryWrapper)
        {
            _bookRepository = repositoryWrapper.BookRepository;
            _publishingHouseRepository = repositoryWrapper.PublishingHouseRepository;
        }

        public IActionResult Index(string publishingHouse = BooksViewModel.AllPublishingHouses)
        {
            var books = GetBooks(publishingHouse);

            var publishingHouses = _publishingHouseRepository.FindAll().Select(x => x.Name).ToList();
            publishingHouses.Add(BooksViewModel.AllPublishingHouses);

            var publishingHousesSelect = new SelectList(publishingHouses);

            var booksViewModel = new BooksViewModel
            {
                Books = books,
                PublishingHouses = publishingHousesSelect,
                SelectedPublishingHouse = publishingHouse
            };

            return View(booksViewModel);
        }

        public IActionResult Info(Guid id)
        {
            var book = _bookRepository.FindByCondition(x => x.Id == id).FirstOrDefault();

            if (book == null) return RedirectToAction("Index");

            return View(book);
        }

        private List<Book> GetBooks(string publishingHouse)
        {
            return publishingHouse != BooksViewModel.AllPublishingHouses
                ? _bookRepository.FindByPublishingHouse(publishingHouse).ToList()
                : _bookRepository.FindAll().ToList();
        }

    }
}

Task_7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bookslist.css" />
    <link rel="stylesheet" href="~/css/loadfilestyle.css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Book" asp-action="Index">Dashboard(Books)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Author" asp-action="Index">Dashboard(Authors)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>